[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.10", features = ["attributes"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"